### ISSUE TITLE
Ignore block not working

### ISSUE THREAD

**Issue by carjessu-trm** [theappnest/terraform-monorepo-action#254]
When using the latest release: 

```yaml
jobs:
  modules:
    runs-on: ubuntu-latest
    steps:
      - uses: theappnest/terraform-monorepo-action@master
        id: modules
        with:
          mode: all
          ignore: |
            */*
            !**/bootstrap/
    outputs:
      modules: ${{ steps.modules.outputs.modules }}
```

We are attempting to only use folders called bootstrap. An example of the file-structure as follows: 
```
.
├── README.md
├── bootstrap
│   └── main.tf
└── gcp
    ├── folders
    │  ├── project
    │  │  │  └── bootstrap
    │  │  │  │   └── main.tf
    │  │  │  └── not-bootstrap
    │  │  │      └── main.tf
```

This results in the module only finding the root level bootstrap folder. When removing the ignore block, the action does correctly find all the modules specified in our repository. Given that this project seems to use https://www.npmjs.com/package/ignore, it should simply just work. Anything we can test to make this work for our use case?
